version: '2'

services:
  web:
    build: .
    volumes:
      - ./src:/opt/app/src
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: comprio
      PGDATABASE: comprio
      PGPASSWORD: secret
      # PGSSLMODE: require
      PGPOOLMAX: 10
      PGPOOLMIN: 4
      PGPOOLIDLE: 10000 # 10s
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - '8080:8080'
    entrypoint: ./scripts/wait.sh db:5432 -- npm run dev

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: comprio
